SELECT 
    count(a.COLUMN_NAME) as cnt
FROM 
    (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'banking' AND TABLE_NAME = 'customers') a
    LEFT JOIN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'banking_staging' AND TABLE_NAME = 'customers_stg') b ON a.COLUMN_NAME = b.COLUMN_NAME
WHERE 
    b.COLUMN_NAME IS NULL;